name: SAA

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Working
        env: |
          PUSHSCKEY: ${{secrets.PUSHSCKEY}}
        run: |
          python3 ./code/SAA_main.py